export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_IS_READY = "SET_IS_READY";

export const FETCH_RECCOMENDED_PRODUCTS = "FETCH_RECCOMENDED_PRODUCTS";
export const FETCH_RECCOMENDED_PRODUCTS_SUCCESS = "FETCH_RECCOMENDED_PRODUCTS_SUCCESS";

export const SET_CATEGORY_FILTER = "SET_CATEGORY_FILTER";