export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCT_SINGLE = "SET_PRODUCT_SINGLE";

export const SET_PRODUCT_BY_SLUG = "SET_PRODUCT_BY_SLUG";
export const SET_PRODUCT_BY_SLUG_SUCCEEDED = "SET_PRODUCT_BY_SLUG_SUCCEEDED";
export const SET_PRODUCT_BY_SLUG_FAILED = "SET_PRODUCT_BY_SLUG_FAILED";

export const SET_CURRENT_PRODUCT_SLUG = "SET_CURRENT_PRODUCT_SLUG";

export const SET_PRODUCT_COMMENTS = "SET_PRODUCT_COMMENTS";
export const SET_PRODUCT_COMMENTS_BY_SLUG = "SET_PRODUCT_COMMENTS_BY_SLUG";
export const SET_PRODUCT_COMMENTS_BY_SLUG_SUCCEEDED = "SET_PRODUCT_COMMENTS_BY_SLUG_SUCCEEDED";
export const SET_PRODUCT_COMMENTS_BY_SLUG_FAILED = "SET_PRODUCT_COMMENTS_BY_SLUG_FAILED";

export const REMOVE_COMMENT_BY_ID = "REMOVE_COMMENT_BY_ID";
export const REMOVE_COMMENT_BY_ID_SUCCEEDED = "REMOVE_COMMENT_BY_ID_SUCCEEDED";

export const SHOW_ALL = 'SHOW_ALL';
export const SCRUB = 'SCRUB';
export const BESTSELLER = 'BESTSELLER';
export const FACE = 'FACE';
export const BODY = 'BODY';

export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_FILTER = 'SET_FILTER';
export const SHOW_PRODUCTS_BY_CATEGORY_SHOP = 'SHOW_PRODUCTS_BY_CATEGORY_SHOP';
export const SORT_PRODUCTS_SHOP = 'SORT_PRODUCTS_SHOP';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';






