export const SET_DOYOUKNOWS = 'SET_DOYOUKNOWS';
export const SET_DOYOUKNOWS_SUCCEEDED = 'SET_DOYOUKNOWS_SUCCEEDED';
export const SET_DOYOUKNOWS_FAILED = 'SET_DOYOUKNOWS_FAILED';

export const SET_SINGLE_DOYOUKNOW = 'SET_SINGLE_DOYOUKNOW';
export const SET_SINGLE_DOYOUKNOW_SUCCEEDED = 'SET_SINGLE_DOYOUKNOW_SUCCEEDED';
export const SET_SINGLE_DOYOUKNOW_FAILED = 'SET_SINGLE_DOYOUKNOW_FAILED';