export const SET_STOCKS = 'SET_STOCKS';
export const SET_STOCKS_SUCCEEDED = 'SET_STOCKS_SUCCEEDED';
export const SET_STOCKS_FAILED = 'SET_STOCKS_FAILED';

export const SET_SINGLE_STOCKS = 'SET_SINGLE_STOCKS';
export const SET_SINGLE_STOCKS_SUCCEEDED = 'SET_SINGLE_STOCKS_SUCCEEDED';
export const SET_SINGLE_STOCKS_FAILED = 'SET_SINGLE_STOCKS_FAILED';