export const SET_VIDEOTIPS = 'SET_VIDEOTIPS';
export const SET_VIDEOTIPS_SUCCEEDED = 'SET_VIDEOTIPS_SUCCEEDED';
export const SET_VIDEOTIPS_FAILED = 'SET_VIDEOTIPS_FAILED';

export const SET_VIDEOTIP_SINGLE = 'SET_VIDEOTIP_SINGLE';
export const SET_VIDEOTIP_SINGLE_SUCCEEDED = 'SET_VIDEOTIP_SINGLE_SUCCEEDED';
export const SET_VIDEOTIP_SINGLE_FAILED = 'SET_VIDEOTIP_SINGLE_FAILED';